# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "6.0.0"
    haproxy:
      repo: "puppetlabs-haproxy"
      ref: "4.1.0"
    apt:
      repo: "puppetlabs-apt"
      ref: "7.1.0"
    registry:
      repo: "puppetlabs-registry"
      ref: "2.1.0"
    inifile:
      repo: "puppetlabs-inifile"
      ref: "3.1.0"
    archive:
      repo: "puppet-archive"
      ref: "3.2.1"
    concat:
      repo: "puppetlabs-concat"
      ref: "6.1.0"
    firewall:
      repo: "puppetlabs-firewall"
      ref: "2.1.0"
    translate:
      repo: "puppetlabs-translate"
      ref: "2.0.0"
    ntp:
      repo: "puppetlabs-ntp"
      ref: "8.0.0"
    consul:
      repo: "KyleAnderson-consul"
      ref: "5.1.0"
    systemd:
      repo: "camptocamp-systemd"
      ref: "2.6.0"
    hiera_http:
      repo: "crayfishx-hiera_http"
      ref: "3.4.0"
    reboot:
      repo: "puppetlabs-reboot"
      ref: "2.2.0"
    timezone:
      repo: "saz-timezone"
      ref: "3.4.0"
    debconf:
      repo: "stm-debconf"
      ref: "2.3.0"
    netplan:
      repo: "zehweh-netplan"
      ref: "0.1.9"
    golang:
      repo: "dcoxall-golang"
      ref: "1.2.0"
    puppetdb:
      repo: "puppetlabs-puppetdb"
      ref: "7.4.0"
    postgresql:
      repo: "puppetlabs-postgresql"
      ref: "6.2.0"
    puppetboard:
      repo: "puppet-puppetboard"
      ref: "5.0.0"
    python:
      repo: "puppet-python"
      ref: "3.0.1"
    apache:
      repo: "puppetlabs-apache"
      ref: "5.1.0"
    sensu:
      repo: "sensu-sensu"
      ref: "3.9.0"
    nginx:
      repo: "puppet-nginx"
      ref: "1.0.0"
    nagios:
      repo: "concrete-nagios"
      ref: "2.5.0"
    datacat:
      repo: "richardc-datacat"
      ref: "0.6.2"
    htpasswd:
      repo: "leinaddm-htpasswd"
      ref: "0.0.3"
    epel:
      repo: "stahnma-epel"
      ref: "1.3.1"
    httpauth:
      repo: "jamtur01-httpauth"
      ref: "0.0.5"
    grafana:
      repo: "puppet-grafana"
      ref: "6.0.0"
    statsd:
      repo: "jdowning-statsd"
      ref: "3.1.0"
    dnsmasq:
      repo: "saz-dnsmasq"
      ref: "1.4.0"
    resolv_conf:
      repo: "saz-resolv_conf"
      ref: "4.1.0"
    
